// <auto-generated />
using BookStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Api.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    partial class BookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Api.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            Pages = 180,
                            Price = 7.99m,
                            Publisher = "Scribner",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            Pages = 281,
                            Price = 8.99m,
                            Publisher = "J.B. Lippincott & Co.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            Pages = 328,
                            Price = 6.99m,
                            Publisher = "Secker & Warburg",
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            Pages = 635,
                            Price = 9.99m,
                            Publisher = "Harper & Brothers",
                            Title = "Moby Dick"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Leo Tolstoy",
                            Genre = "Historical",
                            Pages = 1225,
                            Price = 12.99m,
                            Publisher = "The Russian Messenger",
                            Title = "War and Peace"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            Pages = 279,
                            Price = 5.99m,
                            Publisher = "T. Egerton",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            Pages = 214,
                            Price = 6.99m,
                            Publisher = "Little, Brown and Company",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Pages = 310,
                            Price = 8.99m,
                            Publisher = "George Allen & Unwin",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Ray Bradbury",
                            Genre = "Dystopian",
                            Pages = 194,
                            Price = 7.99m,
                            Publisher = "Ballantine Books",
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Charlotte Brontë",
                            Genre = "Romance",
                            Pages = 500,
                            Price = 6.99m,
                            Publisher = "Smith, Elder & Co.",
                            Title = "Jane Eyre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
